# Generated by Django 4.0.3 on 2022-03-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measurement_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='id_sensor',
        ),
        migrations.AddField(
            model_name='measurement',
            name='id_sensor_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
