# Generated by Django 4.0.3 on 2022-03-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_remove_measurement_id_sensor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='id_sensor_id',
            new_name='sensor',
        ),
    ]
